#!/usr/bin/env bash
# Script that will display information about subdomains

DNS_info () {
    ANSWER=$(dig +short "$2")
    if [[ -n "$ANSWER" ]]; then
        echo "The subdomain $1 is an A record and points to $ANSWER"
    else
        echo "No record found for $1"
    fi
}

if [[ $# -eq 1 ]]; then
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for i in "${subdomains[@]}"; do
        CONCAT="$i.$1"
        DNS_info "$i" "$CONCAT"
    done
elif [[ $# -eq 2 ]]; then
    CONCAT="$2.$1"
    DNS_info "$2" "$CONCAT"
else
    echo "Usage: $0 domain [subdomain]"
fi
