#!/usr/bin/env bash
# Configure Nginx to serve a custom 404 page with "Ceci n'est pas une page"

# Update package lists and install Nginx
apt-get update -y
apt-get install -y nginx

# Remove the default index page (if exists)
rm -f /var/www/html/index.nginx-debian.html

# Create an index.html file
echo "Hello World!" > /var/www/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Custom 404 error page
    error_page 404 /404.html;
}
EOF

# Ensure Nginx is using the updated configuration
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
service nginx restart
