#!/usr/bin/env bash
# Script to configure Nginx with a custom HTTP header (X-Served-By)

# Get the hostname of the server
HOSTNAME=$(hostname)

# Update and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Add the custom header in the Nginx configuration
sudo sed -i "/server_name _;/a \\\tadd_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default

# Reload Nginx to apply changes
sudo systemctl restart nginx
